### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/ee_workflows#3]
Hi Falk-  I'm getting the following error when trying to run the simple.py in the raster_extract folder:

(ee_workflows) C:\Users\kklausmeyer\Documents\workspace\ee_workflows\ee_workflows\raster_extract>python simple.py -f example.shp > output.csv
Traceback (most recent call last):
  File "simple.py", line 63, in <module>
    main(args.shapefilename, args.column, args.year)
  File "simple.py", line 34, in main
    ee.Initialize()
  File "C:\Users\kklausmeyer\.conda\envs\ee_workflows\lib\site-packages\ee\__init__.py", line 105, in Initialize
    ApiFunction.initialize()
  File "C:\Users\kklausmeyer\.conda\envs\ee_workflows\lib\site-packages\ee\apifunction.py", line 152, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\kklausmeyer\.conda\envs\ee_workflows\lib\site-packages\ee\data.py", line 650, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\kklausmeyer\.conda\envs\ee_workflows\lib\site-packages\ee\data.py", line 1196, in send_
    'Server returned HTTP code: %d' % response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404

**Comment by kklausmeyer** [comment]
Thanks to @erdadels for the tip on fixing this issue.  It looks like earthengine-api=0.1.173 is no longer available on conda-forge.  I updated to the latest version (v0.1.250) and was able to get the simple example code to work.  I suggest a modification to the environment.yml file to remove the version dependency.

**Comment by kklausmeyer** [comment]
.yml file is updated-  thanks @postfalk
